#' @export
#'

# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

filter_ped <- function(input_file_name, output_file_name) {
    invisible(.Call('rPCA_filter_ped', PACKAGE = 'rPCA', input_file_name, output_file_name))
}

