# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393
#' Draw PCA
#'
#'R function to make a ped file homzygous
#'
#'@param input_file input file ped
#'@param ouput_file output file ped
#'@keywords plink
#'@export
#'@examples
#'filter_ped("input_file.ped", "output_file.ped")

filter_ped <- function(input_file_name, output_file_name) {
    .Call('rPCA_filter_ped', PACKAGE = 'rPCA', input_file_name, output_file_name)
}

